kind: Pod
apiVersion: v1
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  containers:
  - name: hello-container
    image: openshift/hello-openshift
    ports:
      - containerPort: 8080
